import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700', '900'] })

export const metadata: Metadata = {
  title: 'Home Page - Banner',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.className}`}>
        <div className='min-h-screen flex flex-col'>
          <Header/>
          <main className='flex-grow'>
            {children}
          </main>
          <Footer/>
        </div>
        
        </body>
    </html>
  )
}
